### PR TITLE
Dev ajl

### PR DESCRIPTION
**Pull request by alexjli**
@yuanqing-wang @jchodera just opening a PR as a progress report. 
Commits summary:
- updated methods for `Quantity` to let it play better with `Distribution`
- added `Group`s such as `Solvent`, `Solution`, `ComplexSolution`, which should be able to represent any single-solvent solutions interactions (solvents of solutions mixed are the same).
- added `Group`s `Container` and started `WellArray`, which are designed to hold `Solution`s
- added `Actionable`s, which are modeled off of physical wet-lab instruments (e.g. `Dispenser` models a pipette) and act on `Container`s
- added preliminary code on `Laws`, which are used to model more complex relations e.g. equilibrium
- changed `graph_to_numpyro` to use recursive DFS to evaluate each node in the graph, returns both model trace and final output (notably, does not really use nx graph as of now)

Example usage of solution modeling/inference can be found at `examples/serial-dilutions/playground.ipynb`. Code is still a bit buggy though and Yuanqing and I talked a bit about maybe making some design changes yesterday.

### CODE REVIEW

**Comment by jchodera** [comment]
@alexjli : Instead of using truncated normal distributions, in AssayTools, we found it very useful to work with log quantities for random variables that should be strictly positive. Lognormal distributions are then relatively easy to work with in these log quantities. The only challenge is representing quantities that are really zero, but true zeros also break some of the schemes for solving equilibrium concentrations like [the general binding model](https://assaytools.readthedocs.io/en/latest/theory.html#general-binding-model) (implemented [here](https://github.com/choderalab/assaytools/blob/master/AssayTools/bindingmodels.py)).

**Comment by jchodera** [comment]
@alexjli : Let's go ahead and merge this ASAP once you've checked in all your changes!

**Comment by jchodera** [comment]
Thanks so much @alexjli! Can we go ahead and merge this now that tests pass!

**Comment by alexjli** [comment]
Sorry for the delay! Merging this now

**Comment by jchodera** [comment]
Huzzah! Thanks!

**Pull request merged**
